### ISSUE TITLE
Manip-app slow/not responding

### ISSUE THREAD

**Issue by DominikVincent** [CMM-22/a4#5]
Hi,

when I run the manip-app (debug or release) it is extremely slow (even with the THE_SIM_RUNS_TOO_SLOWLY = true).

Also, I can not move anything in the simulation neither the points nor the arrows. Apparently one should be able to move them. 

What could be the reason for this?

**Comment by DominikVincent** [comment]
Ok, so the reason for not moving the points is that for some reason my mouse cursor is offset by a huge margin.

Still, I run into the issue that it is not optimized after presumably one step. It moves once when I move the points but then stops completely. Further, the gradient checks pass.

**Comment by liyuesolo** [comment]
are you using a Retina screen? try setting I_AM_HAVING_SCREEN_ISSUES = true; maybe try not to have an extra monitor if you are using one.

It should be pretty fast if you are building in release mode.

This sounds like something you need to debug by yourself, maybe try to figure out where does it stop
_Still, I run into the issue that it is not optimized after presumably one step. It moves once when I move the points but then stops completely._

**Comment by DominikVincent** [comment]
After putting in some random print statements and recompiling a lot of times it just worked. I don't know the issue or what made it go away.
